reznikovkg/pedigree

- vue/src/components/pages/Home.vue
- vue/src/components/ui/PhotoPreview.vue
Дворецков #4 
Добавил компонент photopreview, параметры size и photo, исправил названия классов по БЭМ. Сделал везде отступы по 2 пробела.
Сделал наследование стилей, структуру стилей переделал. Выровнял отступы
> #4 PhotoPreview

- package-lock.json
- vue/src/components/forms/EducationForm.vue
- vue/src/components/pages/Home.vue
Боклагов #16 
Добавил компонент формы EducationForm. Параметры: Объект образования(Тип, Уровень, Дата начала обучения, Дата завершения обучения, Название учреждения, Город учреждения)
> #16 EducationForm

- vue/src/components/cards/PersonCard.vue
- vue/src/components/pages/Home.vue
Николаева, Рыкин #3
Добавили компонент карточки человека PersonCard, который получает person
> PersonCard

- package-lock.json
- vue/src/components/pages/PersonPage.vue
- vue/src/router/index.ts
Добавили components/PersonPage.vue
Прописали путь в router в index.js
#9
> Added PersonPage #9

- vue/src/components/pages/CreatePersonPage.vue
- vue/src/components/pages/EditPersonPage.vue
- vue/src/router/index.ts
- vue/src/router/routes.ts
Николаева, Рыкин #28 
Добавили пустые страницы страницы EditPersonPage(со свойством вычисления id по параметру страницы) и CreatePersonPage, 
Добавили маршруты:
1. ```/create```- CreatePersonPage
2. ```/person/:id/edit``` - EditPersonPage 
в indexs.ts и названия в routes.ts
> #28 Создать страницы создания и редактирования человека 

- vue/src/components/forms/MilitaryForm.vue
- vue/src/components/pages/Home.vue
Создал компонент формы MilitaryForm, поместил её в components/forms. Застилизовал элементы в соответствии со скриншотом, в качестве элементов ввода(input, textarea) использовал ElementUI. 
Переименновал лишние классы, сделал CamelCase, сделал автозакрытие тегов и поправил отступы. Всё поправил. Всё добавил, всё приложил.
#33
> Дворецков #33

- vue/src/constants.ts
- vue/src/store/index.js
- vue/src/store/persons.js
Выполнили: Адианова и Дедикова (61 группа)
Задача https://github.com/reznikovkg/pedigree/issues/12: Создать модуль хранилища пользователей
> Убрала все изменения и оставила только глобальный store persons

- vue/src/components/forms/EducationForm.vue
- vue/src/components/pages/Home.vue
Боклагов #34 
Обновил форму EducationForm, элементы ввода(input) использованы из ElementUI
Элементы ввода застилизованы под скриншот
> #34 Updated EducationForm

- vue/src/components/forms/WeddingForm.vue
- vue/src/components/pages/Home.vue
> Плотников, Карцев #35

- vue/src/types/person.ts
Макаров Буркова 62
Описать объект Person на TypeScript
Описать interface для Person со всеми полями #1
Дополнительно опираясь на формы: #16 #17 #30 #33
Разместить в types/person.ts
Был создан интерфейс Person, 
образование
брачный союз 
трудовая деятельность
военная служба
> Описать объект Person на TypeScript #36

- vue/src/components/forms/WeddingForm.vue
- vue/src/components/pages/Home.vue
- vue/src/store/persons.js
- vue/src/types/person.ts
Боклагов #59 Расширил компонент браков, заменил ElInput на ElSelect, значения для select передаются как массив
Значения получаются из persons по условиям(противоположный пол, пересекающиеся даты рождения и смерти)
> #59 Updated WeddingForm

- vue/src/components/App.vue
- vue/src/components/forms/EducationForm.vue
- vue/src/components/forms/MilitaryForm.vue
- vue/src/components/forms/PersonForm.vue
- vue/src/components/forms/WeddingForm.vue
- vue/src/components/forms/WorkForm.vue
- vue/src/components/pages/Settings.vue
Колесникова, Крюков #55
Добавили глобальный класс custom-form в App.vue и использовали его для стилизации всех форм. Формы теперь везде одинаковые. Так же изменили поля с датой, теперь можно полноценно выбирать дату.
> #55 Нормализовать стилизацию форм

- vue/src/components/ui/SimpleButton.vue
> #7, Бибанг Ннама

- vue/src/components/ui/SimpleButton.vue
> Simple Btn

- package-lock.json
- vue/src/components/pages/Home.vue
- vue/src/components/ui/PopOver.vue
> Реализовать компонент всплывающей подсказки #10

- vue/src/components/forms/PersonForm.vue
- vue/src/components/pages/CreatePersonPage.vue
- vue/src/components/pages/EditPersonPage.vue
- vue/src/components/pages/Home.vue
#56 
Вставили форму для страницы создания и редактирования. Значение формы в data разместили как поле form. Вытянули данные через модуль хранилища в mouted  и поместили в form.  Добавлять нового пользователя в хранилище теперь можно по клику, при редактировании заменяется в хранилище.
> Плотников, Карцев #56

- vue/src/components/cards/PersonCard.vue
- vue/src/components/pages/Home.vue
- vue/src/components/pages/PersonPage.vue
#27
Изменили страницы PersonPage, добавив на них карточку человека с добавленным на неё изображением. Добавили редирект с главной страницы на /person/1.
Данные для страницы берутся через айди.
> Расширение страницы человека #27

- vue/src/components/cards/PersonPreviewCard.vue
Макаров Буркова 
https://github.com/reznikovkg/pedigree/issues/57#issue-2161647556
В компонент PersonPreviewCard вставили компонент фотографии параметр подставлять PhotoPreview
> #57 Расширить превью человека 

- vue/src/components/App.vue
- vue/src/components/ui/NavigationPanel.vue
> #71, Сантиаго Нве Бибанг Ннама

- vue/src/components/ui/NavigationPanel.vue
- vue/src/components/ui/SimpleButton.vue
> #90 , Сантиаго Нве Бибанг Ннама

- vue/src/store/modals.js
- vue/src/store/persons.js
- vue/src/store/services/common.js
Извините, что пришлось создать новый PR, у меня проблемы с гитом были, не то заклонил. Добавил последние исправления
#38
> Стандартные сервисы #38

- vue/src/store/settings.js
Там после ребейзов дева криво конфликт был порезолвлен, строчка потерялась.
> Hotfix 54 Будиловский, Смирнов

- vue/src/components/cards/PersonCard.vue
- vue/src/components/ui/RelateButton.vue
- vue/src/store/persons.js
Написали геттер фильтрации объектов по списку с id ("getChildByIds"). Обновили раздел детей, в карточке человека в разделе Дети получили список детей человека. #75
> #75 Евтеева, Качапин

- package-lock.json
- vue/src/components/pages/Home.vue
- vue/src/components/pages/PersonPage.vue
- vue/src/store/persons.js
Шабанов, Козлитин #76
Если сохранено, то кнопка становится серой и недоступна для нажатия
> Реализовать сохранение страницы просмотра #76

- vue/src/components/cards/PersonCard.vue
- vue/src/components/cards/PersonPreviewCard.vue
- vue/src/components/cards/WidePersonCard.vue
- vue/src/components/forms/EducationForm.vue
- vue/src/components/forms/WeddingForm.vue
- vue/src/components/pages/CreatePersonPage.vue
- vue/src/components/pages/EditPersonPage.vue
- vue/src/components/pages/PersonList.vue
- vue/src/components/pages/PersonPage.vue
- vue/src/components/pages/SettingsPage.vue
- vue/src/components/parts/EducationItem.vue
- vue/src/components/parts/EducationList.vue
- vue/src/components/parts/MilitaryItem.vue
- vue/src/components/parts/MilitaryList.vue
- vue/src/components/parts/ModalContainer.vue
- vue/src/components/parts/WeddingItem.vue
- vue/src/components/parts/WeddingsList.vue
- vue/src/components/ui/InputHelper.vue
- vue/src/components/ui/NavigationPanel.vue
- vue/src/components/ui/PopOver.vue
- vue/src/store/persons.js
Николаева, Рыкин #102 
Поправили стиль кода, названия полей, чтобы соответствовали объектам в types/person.ts
Исправили ошибку в PersonList
> #102 Задача на рефакторинг

- vue/src/components/cards/PersonCard.vue
- vue/src/components/cards/PersonPreviewCard.vue
- vue/src/components/forms/PersonForm.vue
- vue/src/components/ui/RelateButton.vue
- vue/src/services/person.ts
- vue/src/store/persons.js
- vue/src/types/person.ts
- vue/src/utils/mask.js
Внедрили скрытый режим
Выпадающий список на странице редактирования
Видимый пользователь
Скрытый пользователь
Скрытый ребенок
> #104 Внедрение скрытого режима, Будиловский, Смирнов

- vue/src/components/cards/PersonCard.vue
- vue/src/store/persons.js
> #61 , Сантиаго Нве Бибанг Ннама

- vue/src/components/forms/ChildForm.vue
- vue/src/components/forms/PersonForm.vue
> Связать все формы #100

- vue/src/components/forms/PersonForm.vue
- vue/src/services/person.ts
- vue/src/types/person.ts
https://github.com/reznikovkg/pedigree/issues/100
Жибров и Долженкова
Внесли правки
> Связать все формы #100 правки

- vue/src/components/cards/PersonCard.vue
- vue/src/components/cards/WidePersonCard.vue
- vue/src/components/pages/Home.vue
- vue/src/components/ui/RelateButton.vue
- vue/src/router/index.ts
- vue/src/services/formatPersonName.ts
- vue/src/utils/mask.js
#98  Функция для ФИО
Реализовали функции для ФИО, разместить в каталоге сервисов.
Написали функцию, в которую передается объект person, и параметр short=false.
Функция возвращает строку ФИО в полном формате (по найденным полям) при параметре short=false и в сокращенном виде при short=false.
Подключили в вывод компонентов данную функцию.
> #98 Макаров, Буркова 

- vue/src/components/pages/CreatePersonPage.vue
- vue/src/components/pages/EditPersonPage.vue
- vue/src/components/pages/Home.vue
- vue/src/components/pages/PersonList.vue
- vue/src/components/ui/HeaderComponent.vue
- vue/src/components/ui/NavigationPanel.vue
- vue/src/main.js
- vue/src/router/routesPlugin.js
Задача https://github.com/reznikovkg/pedigree/issues/143  Ничуговский
Подключил плагин с константами routesPlugin в main.js. Также во всех файлах, где используются, заменил маршрутизации и названия роутов
> #143 Константы для роутинга

- vue/src/components/cards/PersonCard.vue
- vue/src/components/forms/PersonForm.vue
- vue/src/components/pages/PersonList.vue
- vue/src/services/person.ts
- vue/src/store/persons.js
- vue/src/types/person.ts
#151
Выполнили:
Смирнов, Будиловский
Описание:
Добавлен тогл на страницу со списком персон. Список фильтруется по этому тоглу. (Показывать всех / Показать доступных)
На всех остальных страницах персоны не отображаются, если их статус removed.
> #151, Смирнов, Будиловский, Полное скрытие персоны

- vue/src/components/pages/PersonList.vue
- vue/src/router/index.ts
> #176, Сантиаго Нве Бибанг Ннама

- vue/src/components/ui/ProgressBar.vue
https://github.com/reznikovkg/pedigree/issues/168 Ничуговский
Добавил components/ui ProgressBar.vue с реализацией самого прогресс бара
> #168 Сделать круговой прогресс бар
